language: python

python:
  - "3.11"
  - "3.10"

cache: pip

install:
  - pip install -U pip aiomysql
  - pip install -U pip aiofiles
  - pip install -e .[ci]

script:
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls
